"""Generate web/data.js — the mode bank consumed by the browser UI.

For square plates: emit just the (n, m) mode list and frequencies; the
JS computes ψ live from cos products (separable, fast).

For circular plates: emit precomputed ψ_{n,m}(x, y) on a 128×128 grid
per mode (Bessel functions are not separable in cartesian coordinates).
Field arrays are encoded as base64 Float32 inline in a JS file so the
page works from file:// without a server.

Run:  python build_web.py
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

import numpy as np
from scipy.special import iv, jv

from chladni import (
    enumerate_circular_modes,
    enumerate_square_modes,
    _bc_entries,
    MATERIALS,
)

# ----------------------------------------------------------------------------
# Defaults — these are baked into data.js. The frontend can rescale
# frequencies later if we add geometry sliders.
# ----------------------------------------------------------------------------

# Steel kitchen plate
SQ_L = 0.20
CI_R = 0.10
H = 0.001
MAT = MATERIALS["steel"]

SQ_MAX_MODE = 16        # n, m in [1, 16] → ~136 modes
CI_MAX_N = 10
CI_MAX_M = 4            # → up to 11*5 = 55 modes; many high-n high-m will be culled
CI_GRID = 128           # field resolution
FREQ_CEIL = 8000.0      # only ship modes below this frequency


def encode_field(arr: np.ndarray) -> str:
    f32 = arr.astype(np.float32, copy=False)
    return base64.b64encode(f32.tobytes()).decode("ascii")


def build_square_bank() -> dict:
    modes_raw = enumerate_square_modes(SQ_L, H, **MAT, max_mode=SQ_MAX_MODE)
    modes: list[dict] = []
    for mode in modes_raw:
        if mode.f > FREQ_CEIL:
            continue
        modes.append(
            {
                "n": mode.n,
                "m": mode.m,
                "f": round(mode.f, 4),
                "diagonal": mode.n == mode.m,
            }
        )
    modes.sort(key=lambda d: d["f"])
    return {
        "L": SQ_L,
        "h": H,
        "E": MAT["E"],
        "rho": MAT["rho"],
        "nu": MAT["nu"],
        "modes": modes,
    }


def build_circular_bank() -> dict:
    nu = MAT["nu"]
    modes_raw = enumerate_circular_modes(
        CI_R, H, **MAT, max_n=CI_MAX_N, max_m=CI_MAX_M
    )

    # Precompute the (x, y) → (r, θ) grid once.
    xs = np.linspace(-CI_R, CI_R, CI_GRID)
    ys = np.linspace(-CI_R, CI_R, CI_GRID)
    X, Y = np.meshgrid(xs, ys)
    r = np.hypot(X, Y)
    theta = np.arctan2(Y, X)
    mask_outside = r > CI_R
    r_safe = np.clip(r, 1e-12, CI_R)

    modes: list[dict] = []
    for mode in modes_raw:
        if mode.f > FREQ_CEIL:
            continue
        if mode.lam is None:
            continue
        n = mode.n
        lam = mode.lam
        s = lam * r_safe / CI_R
        Jn_s = jv(n, s)
        In_s = iv(n, s)
        # alpha satisfies M_r = 0 at r = R
        M_J, M_I_s, _, _ = _bc_entries(lam, n, nu)
        alpha = -M_J / (np.exp(lam) * M_I_s)
        radial = Jn_s + alpha * In_s
        psi = radial * np.cos(n * theta)
        psi[mask_outside] = 0.0
        # Normalize peak to 1 so all modes have comparable visual weight.
        peak = float(np.max(np.abs(psi)))
        if peak > 0:
            psi = psi / peak
        modes.append(
            {
                "n": n,
                "m": mode.m,
                "f": round(mode.f, 4),
                "lambda": round(lam, 6),
                "field_b64": encode_field(psi),
            }
        )
    modes.sort(key=lambda d: d["f"])

    return {
        "R": CI_R,
        "h": H,
        "E": MAT["E"],
        "rho": MAT["rho"],
        "nu": nu,
        "grid": CI_GRID,
        "modes": modes,
    }


def main() -> None:
    out_dir = Path(__file__).parent / "web"
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Building square mode list …")
    sq = build_square_bank()
    print(f"  {len(sq['modes'])} modes, freq range "
          f"{sq['modes'][0]['f']:.1f}-{sq['modes'][-1]['f']:.1f} Hz")

    print("Building circular mode bank with precomputed fields …")
    ci = build_circular_bank()
    print(f"  {len(ci['modes'])} modes at {CI_GRID}×{CI_GRID}, freq range "
          f"{ci['modes'][0]['f']:.1f}-{ci['modes'][-1]['f']:.1f} Hz")

    bank = {
        "version": 1,
        "freq_ceil": FREQ_CEIL,
        "square": sq,
        "circle": ci,
    }

    out_path = out_dir / "data.js"
    out_path.write_text(
        "// auto-generated by build_web.py — do not edit by hand\n"
        "window.CHLADNI_DATA = "
        + json.dumps(bank, separators=(",", ":"))
        + ";\n"
    )
    size_mb = out_path.stat().st_size / (1024 * 1024)
    print(f"\nWrote {out_path} ({size_mb:.2f} MB)")


if __name__ == "__main__":
    main()
